server {                                                                                             
        listen 80;                                                                                       
                                                                                                         
        # Tell Nginx to use Docker's internal DNS                                                        
        resolver 127.0.0.11 valid=10s;                                                                   
                                                                                                         
        location / {                                                                                     
            root /usr/share/nginx/html;                                                                  
            index index.html;                                                                            
            try_files $uri $uri/ /index.html;                                                            
        }                                                                                                
                                                                                                         
        location /api/ {                                                                                 
            # Notice we removed /api/ from the URL here!                                                 
            set $api_backend http://backend:3000;                                                        
            proxy_pass $api_backend;                                                                     
            proxy_set_header Host $host;                                                                 
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;                                 
        }                                                                                                
                                                                                                         
        location = /widget.js {                                                                          
            # Notice we removed /widget.js from the URL here!                                            
            set $script_backend http://backend:3000;                                                     
            proxy_pass $script_backend;                                                                  
            proxy_set_header Host $host;                                                                 
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;                                 
        }                                                                                                
    }